### ISSUE TITLE
Compile on Arduino IDE 1.8.8 fails

### ISSUE THREAD

**Issue by MungoBerry** [dmadison/ArduinoXInput#26]
Hi,

I'm trying to use your library with a Pro Micro but i get a compilation error:

> cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

Any hints?

Thank you.

**Comment by dmadison** [comment]
That typically indicates that the boards files are not installed properly and cannot link back to the main compilation files.

I would recommend removing the XInput boards files, re-reading the instructions for how to install them, and trying again.

**Comment by MungoBerry** [comment]
I've solved switching from 1.8.8 to 1.8.10
Thanks.
